apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-k8s-demo
  template:
    metadata:
      labels:
        app: jenkins-k8s-demo
    spec:
      containers:
        - name: jenkins-k8s-demo
          image: rakshith3/jenkins-k8s-demo:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-k8s-demo-svc
spec:
  selector:
    app: jenkins-k8s-demo
  type: NodePort
  ports:
    - port: 3000         # Port exposed inside the cluster
      targetPort: 3000   # Port your container is listening on
      nodePort: 32000    # Port exposed on your node (30000-32767)
