apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-k8s-demo
  template:
    metadata:
      labels:
        app: jenkins-k8s-demo
    spec:
      containers:
        - name: jenkins-k8s-demo
          image: YOUR_REGISTRY/jenkins-k8s-demo:${BUILD_TAG}
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
