apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-k8s-demo
  template:
    metadata:
      labels:
        app: jenkins-k8s-demo
    spec:
      containers:
        - name: jenkins-k8s-demo
          image: rakshith3/jenkins-k8s-demo:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
