apiVersion: v1
kind: Service
metadata:
  name: jenkins-k8s-demo-svc
spec:
  selector:
    app: jenkins-k8s-demo
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          # Service port inside cluster
      targetPort: 3000  # Matches containerPort in Deployment
      # nodePort: 32000   # Port exposed on the node
