apiVersion: v1
kind: Service
metadata:
  name: jenkins-k8s-demo-svc
spec:
  selector:
    app: jenkins-k8s-demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
