apiVersion: v1
kind: Service
metadata:
  name: jenkins-k8s-demo-svc
spec:
  type: LoadBalancer
  selector:
    app: jenkins-k8s-demo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
